# Generated by Django 5.0.4 on 2024-05-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaLazizApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coverPhoto', models.ImageField(upload_to='static/Photos/')),
                ('mainPhoto', models.ImageField(upload_to='static/Photos/')),
                ('duration', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaLazizApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaLazizApp.user')),
                ('recipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaLazizApp.recipe')),
            ],
        ),
    ]
