# Generated by Django 5.0.6 on 2024-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaLazizApp', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userphoto',
            field=models.ImageField(null=True, upload_to='static/phototos/users/%y/%m/%d'),
        ),
    ]
